(deftheme custom-srcery
  "My variant to scery theme with some monokai colors and fully custom colors.")

(custom-theme-set-faces
 'custom-srcery
 '(default ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :height 113 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FCE8C3" :background "#1C1B19" :stipple nil :inherit nil))))
 '(cursor ((t (:inverse-video t :foreground "#1C1B19" :background "#FCE8C3"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#FBB829"))))
 '(highlight ((t (:weight bold :background "#444444"))))
 '(region ((t (:inverse-video t))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#303030"))))
 '(trailing-whitespace ((t (:background "#EF2F27"))))
 '(font-lock-builtin-face ((t (:foreground "#2C78BF"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#918175"))))
 '(font-lock-constant-face ((t (:foreground "#FF5C8F"))))
 '(font-lock-doc-face ((t (:foreground "#519F50"))))
 '(font-lock-function-name-face ((t (:foreground "#FBB829"))))
 '(font-lock-keyword-face ((t (:foreground "#EF2F27"))))
 '(font-lock-negation-char-face ((t (:foreground "#FF5C8F"))))
 '(font-lock-preprocessor-face ((t (:foreground "magenta"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:foreground "#68A8E4"))))
 '(font-lock-variable-name-face ((t (:foreground "#0AAEB3"))))
 '(font-lock-warning-face ((t (:foreground "#FF8700" :background "#1C1B19"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :inherit (font-lock-comment-face)))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :inherit (font-lock-comment-face)))))
 '(fringe ((t (:foreground "#FCE8C3"))))
 '(header-line ((t (:background "#1C1B19"))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#FCE8C3" :background "#68A8E4"))))
 '(mode-line ((t (:foreground "#918175" :background "#2D2C29"))))
 '(mode-line-buffer-id ((t (:foreground "#FBB829"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 1 :color "#E02C6D" :style nil) :background "#2D2C29"))))
 '(mode-line-inactive ((t (:foreground "#918175" :background "#2D2C29"))))
 '(isearch ((t (:weight bold :underline (:color foreground-color :style line) :background "#444444"))))
 '(isearch-fail ((t (:foreground "#EF2F27"))))
 '(lazy-highlight ((t (:weight bold :background "#444444"))))
 '(match ((t (:weight bold :background "#444444"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'custom-srcery)
