(deftheme custom-monokai
  "Created 2018-10-22.")

(custom-theme-set-variables
 'custom-monokai
 )

(custom-theme-set-faces
 'custom-monokai
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "magenta"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :italic nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic nil))))
 '(font-lock-variable-name-face ((t (:foreground "white"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(c-annotation-face ((((class color) (min-colors 257)) (:inherit font-lock-constant-face)) (((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(button ((t (:underline t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#49483E")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:inherit highlight :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit highlight :background "#3E3E3E"))))
 '(region ((((class color) (min-colors 257)) (:inherit highlight :background "#49483E")) (((class color) (min-colors 89)) (:inherit highlight :background "#474747"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:inherit region :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit region :background "#3E3E3E"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#272822" :weight bold)) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#AE81FF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#F92672")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#64645E")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#49483E" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#1B1E1C" :box (:line-width 1 :color "#474747" :style unspecified)))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#272822" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#3D3D3D" :style unspecified)))))
 '(header-line ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#49483E" :box (:color "#64645E" :line-width 1 :style unspecified))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#474747" :box (:color "#3D3D3D" :line-width 1 :style unspecified)))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#66D9EF" :background "#272822" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 257)) (:inherit shadow)) (((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :underline t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :slant italic)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(isearch ((((class color) (min-colors 257)) (:inherit region :foreground "#272822" :background "#E6DB74")) (((class color) (min-colors 89)) (:inherit region :foreground "#1B1E1C" :background "#CDC673"))))
 '(isearch-fail ((((class color) (min-colors 257)) (:inherit isearch :foreground "#F92672" :background "#272822" :bold t)) (((class color) (min-colors 89)) (:inherit isearch :foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(linum ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#272822" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :inherit default :underline nil))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#FFFACE" :foreground "#272822" :inherit default))))
 '(default ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C")))))

(provide-theme 'custom-monokai)
